---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=999
      - TZ=Etc/UTC
        #- PASSWORD=password #optional
        #- HASHED_PASSWORD= #optional
        #- SUDO_PASSWORD=password #optional
        #- SUDO_PASSWORD_HASH= #optional
        #- PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/leela #optional
    volumes:
      - ~/docker/code-server/appdata:/config
      - ~/docker:/leela  
    ports:
      - 8443:8443
    restart: unless-stopped
