---
version: "2.1"
services:
  resilio-sync:
    container_name: resilio-sync
    image: lscr.io/linuxserver/resilio-sync:latest
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Los_Angeles
    # networks:
    #   - caddy
    # labels:
    #   caddy: sync.planetexpress.casa
    #   caddy.reverse_proxy: "{{upstreams 8888}}"
    #   caddy.tls: internal
    ports:
      - 8888:8888
      - 55555:55555
    volumes:
      - ~/docker/resilio/appdata:/config
      - ~/docker/resilio/downloads:/downloads
      - ~/docker/resilio/sync:/sync
      - /mnt/media:/sync/media
      - /mnt/ROMs:/sync/games
    restart: unless-stopped

# networks:
#   caddy:
#     external: true