services:
  resilio-sync:
    container_name: resilio-sync
    image: lscr.io/linuxserver/resilio-sync:latest
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Los_Angeles
    ports:
      - 8888:8888
      - 55555:55555
    volumes:
    # Leela
      - "/home/jeffrey/LeelaSync:/sync/Leela Sync"
      - /home/jeffrey/docker/resilio/appdata:/config
      - /home/jeffrey/docker/resilio/downloads:/downloads
      - /home/jeffrey/docker/resilio/sync:/sync
    # Nibbler
      - /home/jeffrey/docker/resilio/appdata:/config
      - /mnt/sync:/sync
      - /mnt/media:/sync/Media
      - /mnt/Backups/Signal:/sync/Signal

    restart: unless-stopped