services:
  resilio-sync:
    container_name: resilio-sync
    image: lscr.io/linuxserver/resilio-sync:latest
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Los_Angeles
    ports:
      - 8888:8888
      - 55555:55555
    volumes:
    # Leela
      - "~/LeelaSync:/sync/Leela Sync"
      - ~/docker/resilio/appdata:/config
      - ~/docker/resilio/downloads:/downloads
      - ~/docker/resilio/sync:/sync
    # Nibbler
      - /mnt/media:/sync/media
      - /mnt/ROMs:/sync/ROMs
      - /mnt/Backups/Signal:/sync/Signal
    restart: unless-stopped