---
version: "2.1"
services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Los_Angeles
    volumes:
      - ~/docker/resilio/appdata:/config
      - ~/docker/resilio/downloads:/downloads
      - ~/docker/resilio/sync:/sync
      - /mnt/media:/sync/media
      - /mnt/ROMs:/sync/games
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped