---
version: '3'
services:
  filebot:
    image: jlesage/filebot
    container_name: filebot
    env_file:
      - ../.env
    ports:
      - 5800:5800
    volumes:
      - "/docker/appdata/filebot:/config:rw"
      - "/home/user:/storage:rw"