---
version: '3'
services:
  filebot:
    container_name: filebot
    image: jlesage/filebot
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Los_Angeles     
    ports:
      - 5800:5800
    volumes:
      - "~/docker/filebot/appdata:/config:rw"
      - "/mnt/media:/nas/media:rw"
