---
version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    environment:
      - TZ=America/Los_Angeles
      - WEBPASSWORD=${PI_HOLE_PASSWORD}
    ports:
      - "5553:53/tcp"
      - "5553:53/udp"
      - "8880:80/tcp"
    # Volumes store your data between container upgrades
    volumes:
      - ~/docker/pi-hole/appdata/etc-pihole:/etc/pihole'
      - ~/docker/pi-hole/appdata/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    deploy:
      mode: global
      restart_policy:
        condition: on-failure