# Heimdall
---
version: "2.1"
services:
  heimdall:
    container_name: heimdall
    image: lscr.io/linuxserver/heimdall:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - 10014:80
      - 10015:443
    volumes:
      - ~/docker/heimdall/appdata:/config
    restart: unless-stopped

  cloudflare-heimdall:  
    container_name: cloudflared-heimdall
    image: cloudflare/cloudflared     
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_HEIMDALL}
    mem_limit: 1g
    restart: unless-stopped
