---
version: "2.1"
services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Los_Angeles
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
    mem_limit: 16g
    network_mode: host
    volumes:
      - ~/docker/plex/appdata:/config
      - /mnt/media:/nas/media
    devices:
      - /dev/dri:/dev/dri # Map for hardware acceleration
    restart: unless-stopped
