---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
    env_file:
      - ../.env
    volumes:
      - /docker/plex/appdata:/config
      - /mnt/nibbler/media:/media
    restart: unless-stopped