---
version: "2.1"
services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/resilio/appdata:/config
      - /nibbler/apps/Resilio/downloads:/downloads
      - /nibbler/apps/Resilio/sync:/sync
      - /nibbler/media:/sync/media
      - /nibbler/games:/sync/games
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped