---
version: "3.9"
services:
  serge:
    container_name: serge
    build: 
      context: .
      dockerfile: Dockerfile
      target: release
    volumes:
      - datadb:/data/db
      - weights:/usr/src/app/weights/
      - /etc/localtime:/etc/localtime:ro 
    ports:
      - 8008:8008
    restart: on-failure

volumes:
  datadb:
  weights: