---
version: "3.9"
services:
  serge:
    container_name: serge
    image: ghcr.io/serge-chat/serge:latest
    environment:
      - TZ=America/Los_Angeles
    ports:
      - 8008:8008
    volumes:
      - /home/jeffrey/docker/serge/appdata/weights:/usr/src/app/weights
      - /home/jeffrey/docker/serge/appdata/datadb:/data/db
    devices:
      - /dev/dri:/dev/dri # Map for hardware acceleration
    restart: on-failure

  cloudflare-serge: 
    container_name: cloudflared-serge 
    image: cloudflare/cloudflared     
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_SERGE}
    mem_limit: 1g
    restart: unless-stopped

volumes:
  datadb:
  weights:
