---
version: "3"
services:
  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ~/docker/yacht/appdata:/config
      - /var/run/docker.sock:/var/run/docker.sock
        #  volumes:
        #    yacht:
