---
version: "3.0"
services:
  openwakeword:
    container_name: openwakeword
    image: rhasspy/wyoming-openwakeword
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Los_Angeles
    mem_limit: 8g
    ports:
        - 10400:10400
    volumes:
      - ~/docker/wyoming/appdata/openwakeword:/data
      - ~/docker/wyoming/appdata/openwakeword:/custom
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      --preload-model ok_nabu
      --custom-model-dir /custom
    restart: unless-stopped
  porcupine:
    container_name: porcupine
    image: rhasspy/wyoming-porcupine1
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Los_Angeles
    mem_limit: 8g
    ports:
        - 10500:10400
    volumes:
      - ~/docker/wyoming/appdata/porcupine:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  faster-whisper:
    container_name: faster-whisper
    image: rhasspy/wyoming-faster-whisper
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Los_Angeles
    mem_limit: 2g
    ports:
      - 10300:10300
    volumes:
      - ~/docker/wyoming/appdata/faster-whisper:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: --model base-int8 --language en
    restart: unless-stopped
  piper:
    container_name: piper
    image: rhasspy/wyoming-piper
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Los_Angeles
    mem_limit: 1g
    ports:
      - 10200:10200
    volumes:
      - ~/docker/wyoming/appdata/piper:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: --voice en_US-norman-medium
    restart: unless-stopped
