---
version: "3"
services:
# Tunnel used for TrueNAS
 cloudflare-truenas:
   image: cloudflare/cloudflared:latest 
   container_name: cloudflared-truenas
   command: tunnel run
   environment:
     - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_NAS}
   restart: unless-stopped
