---
version: '3.3'
services:
    tailscale:
        container_name: tailscaled
        image: tailscale/tailscale
        environment:
            - TS_AUTHKEY=${AUTH_KEY}
        network_mode: host
        volumes:
            - ~/docker/tailscale:/var/lib
            - /dev/net/tun:/dev/net/tun
